### ISSUE TITLE
Misidentification of Broadcom / LSI MegaRAID SAS 2108 [Liberator]

### ISSUE THREAD

**Issue by jnyhuis** [realasmo/bash#1]
ASMO's script is great and covers the controller types on most of our servers.  However, it fails to identify our Broadcom / LSI MegaRAID SAS 2108 [Liberator] cards.  Our OS is CentOS Linux release 7.7.1908 (Core).

lspci reports:
lspci |grep RAID | grep Intel -v |head -1
03:00.0 RAID bus controller: Broadcom / LSI MegaRAID SAS 2108 [Liberator] (rev 05)

As line 658 matches arg5 (using awk '{print $5}'), my return is "Broadcom" not "LSI" causing the script to fail to identify our cards.

I corrected this by modifying line 658 using an "or" statement.

        if [[ ${hw_card_model} = "LSI" ]]; then
changed to:
        if [[ ${hw_card_model} = "LSI" || ${hw_card_model} = "Broadcom" ]]; then

I have not had any miss-identifications keying on "Broadcom" but I am a small sample set.  If you like my change, please feel free to add it to your code base.  

Thanks again to asmo for sharing your hard work!

Thanks,
John N.

**Comment by realasmo** [comment]
Thank you for reporting it, Broadcom/LSI issue has been corrected and few more features added.
